# Sort, Search & Counting function:

In [2]:
import numpy as np

In [6]:
# Declaring an array:
arr = np.array([3,45,2,13,45,32,24,13,67,45,2,97,90,221,123])

In [7]:
# Sorting: {By default ascending}
np.sort(arr)

array([  2,   2,   3,  13,  13,  24,  32,  45,  45,  45,  67,  90,  97,
       123, 221])

In [8]:
# Where to put given element in existing array: Returns index
np.searchsorted(arr, 34)

8

In [9]:
arr1 = np.array([0,4423,31,1322,42,0,0,0,0,0,0])

In [10]:
# Count of non-zeros data from an array:
np.count_nonzero(arr1)

4

In [11]:
arr

array([  3,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

In [13]:
# Filter out data more than 'n' and show their indexes : returns index
np.where(arr > 45)

(array([ 8, 11, 12, 13, 14]),)

In [14]:
# Extract data based on given condition:
np.extract(arr > 3 ,arr)

array([ 45,  13,  45,  32,  24,  13,  67,  45,  97,  90, 221, 123])

# Numpy --> Byte Swapping
Converts given data into their bytes form

In [15]:
arr

array([  3,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

In [18]:
# Converts to byte 
arr.byteswap()

array([  216172782113783808,  3242591731706757120,   144115188075855872,
         936748722493063168,  3242591731706757120,  2305843009213693952,
        1729382256910270464,   936748722493063168,  4827858800541171712,
        3242591731706757120,   144115188075855872,  6989586621679009792,
        6485183463413514240, -2522015791327477760,  8863084066665136128])

# Numpy --> Copies & Views

In [19]:
arr

array([  3,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

In [21]:
# Creates copy of the array and stores in diff location. known as Deep Copy
a = np.copy(arr)

In [22]:
# Using view() : similar to Swallow copy {At same location reference is created}
b = arr.view()

In [ ]:
b = arr

In [23]:
b

array([  3,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

In [24]:
a

array([  3,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

In [28]:
b[0] = 56

In [27]:
arr

array([ 56,  45,   2,  13,  45,  32,  24,  13,  67,  45,   2,  97,  90,
       221, 123])

# Numpy --> Matrix Library

In [29]:
import numpy.matlib as nm
# Matrix is sub-class of array
# All operations are available in matrix library same as arrays.

In [30]:
# Generates matrices instead of array :> Always 2-D is generated
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
# generate ones with given dimension shape:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
# Generate identity matrix:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy --> Linear Algebra

>>Mainly used in Machine Learning concept.

ex: dot product, eagan vector, eagan values

In [33]:
arr1  = np.random.randint([[2,3],[4,5]])

In [34]:
arr2 = np.random.randint([[5,3],[2,5]])

In [35]:
# Calculate dot product : matrix multiplication
np.dot(arr1,arr2)

array([[0, 0],
       [6, 7]])

In [36]:
# Same as @: Available as symbol as well as function : dot()
arr1@arr2

array([[0, 0],
       [6, 7]])