# Python- NumPy

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
np.array(l)

array([1, 2, 3, 4])

In [4]:
# array is a super-class in numpy
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [7]:
# type 'ndarray' >represents n-dimensional array data
np.array([[1,2],[3,4]]) #2-D array

array([[1, 2],
       [3, 4]])

In [8]:
# 2-d data can be represnted in 2-D co-ordinates

In [9]:
# Maximum 3-D data can be represented:


In [10]:
# COnverts into array
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
a=[2,3,4]

In [12]:
# Convert into array:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
# Matrix is by-default 2-D array {Sub-set of array}
b= np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)
# Unable to convert to array: matrix can't be converted into array using asannyarray

matrix([[1, 2, 3, 4]])

# Re-assignment of data inside array

In [17]:
a=np.array(l)

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c = a

In [20]:
c

array([1, 2, 3, 4])

In [21]:
a

array([1, 2, 3, 4])

In [22]:
c[0]

1

In [23]:
c[0] = 100

In [24]:
c

array([100,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
# c -> used as reference 
# 'c' is Swalllow copy of 'a'


#Copy >> copies array and allocate at new location
# 'd' is Deep copy of 'a'

In [27]:
d = np.copy(a)

In [28]:
d

array([100,   2,   3,   4])

In [29]:
a

array([100,   2,   3,   4])

In [30]:
a[1]= 400

In [31]:
a

array([100, 400,   3,   4])

In [33]:
d

array([100,   2,   3,   4])

# Functions to generate different Arrays in numPy:

In [34]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
# Using iterables>>

In [37]:
iterable = (i*i for i in range(5))

In [38]:
# fromiter function:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
# using fromstring
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [40]:
np.fromstring('4,5',sep=',')

array([4., 5.])

# Data-Types in NumPy:

In [41]:
l=[2,3,4,5,6]

In [42]:
ar = np.array(l)

In [43]:
ar

array([2, 3, 4, 5, 6])

In [44]:
# to check dimension of array:
ar.ndim

1

In [46]:
ar2 = np.array([[1,2,3,4],[3,4,5,6]])

In [47]:
ar2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [48]:
ar2.ndim

2

In [49]:
# To check size of array (count of elements)
ar.size

5

In [50]:
ar2.size

8

In [51]:
# To display shape of array
ar.shape

(5,)

In [52]:
ar2.shape  #(rows, cols)

(2, 4)

In [57]:
# To serach data-type of elements
ar.dtype

dtype('int64')

In [58]:
ar2.dtype

dtype('int64')

In [59]:
ar22 = np.array([(23,34,56),(1.4,24,55)])

In [60]:
ar22

array([[23. , 34. , 56. ],
       [ 1.4, 24. , 55. ]])

In [61]:
ar22.dtype  #even single occurence of float data makes whole as flot

dtype('float64')

In [65]:
# To produce floating point using range : No, it's not possible
# Range always allow integer value
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

# More Array generation using numpy in-built functions:

In [68]:
# using numpy:we can produce floating numbers:
np.arange(2.3,5.6)
np.arange(2.3,5.6,.3)  #jump can also be defined

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [69]:
# Convert array to list:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [70]:
# linspace function: Takes a line 1 to 5 and divide into 10 equal spaces
np.linspace(1,5,10)  #generator function


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
# zeros()
np.zeros(5)  #1-D

array([0., 0., 0., 0., 0.])

In [72]:
# 2-D
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
# 3-D array
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [76]:
# 4-D array
ar4= np.zeros((3,4,2,3))  # 2x3 >4 such matrixes > repeat 3 times

In [77]:
ar4.ndim

4

In [78]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [79]:
# ones()
# 1-D
np.ones(4)

array([1., 1., 1., 1.])

In [80]:
# 2-D
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
# 3-D
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [82]:
on = np.ones((2,3,2))

In [83]:
# Addition with array elements:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [86]:
on*2*5

array([[[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]]])

In [89]:
# empty()
np.empty((3,4))

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [95]:
# identity matrixes: eye() Square matrix dimension is same
# determiner is 1 and 1 can be found as diagonals
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [97]:
# logspace(): calculate log between given range
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [98]:
# base can also be defined for calculating log
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

# Famous and Most useful functions of numpy:

In [100]:
# randn() function
arr = np.random.randn(3,4)  #(3 rows, 4 cols)
# Generates such set of data where,
# mean of data == 0
# Standard deviation == 1 (standard normal distribution)

In [101]:
import pandas as pd

In [102]:
# Convert into dataframe:
pd.DataFrame(arr)

0         1         2         3
0  1.040679  0.313878 -1.617395  0.019175
1  0.134479 -0.915051 -0.260357  0.793743
2  0.321324 -0.394728  0.235487  0.764169

In [105]:
# rand() function:
np.random.rand(3,4)
# rand() generates some random set of data every time generate diff set of data

array([[0.51668658, 0.90232327, 0.1879032 , 0.5979953 ],
       [0.91641877, 0.51230351, 0.73012649, 0.33369975],
       [0.83042797, 0.02355249, 0.704426  , 0.22273338]])

In [106]:
# randint(): generates random integers only
np.random.randint(1,110,(3,4))


array([[  6,  24,  87,  96],
       [102,  16,   9, 103],
       [ 35, 105,  48,  93]])

In [107]:
# Produce random data having 300 rows and 400 cols:
np.random.randint(1,110,(300,400))

array([[ 56,  55, 109, ...,  30,  33,  23],
       [ 68,  44,  20, ..., 105,  89,  43],
       [ 43,   3,  44, ...,  47,  73,   8],
       ...,
       [ 66,  16,  68, ...,  81,  66,  79],
       [ 84,  37,  74, ...,  87,   2,  29],
       [  9,  77,  78, ...,  81,  84,  63]])

In [108]:
# Convert into data-frame:
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     91   77   35    7   71    2   19   56   51   34  ...   92   70   99   
1     47   57   82  107   26   13   77   27   80   84  ...  106   53  105   
2    102   91   88   96   25   59   33   75   53   76  ...    1   76   25   
3     63   65   53   20   99   26   43   32   64    2  ...   27   88   93   
4     62   38   29   47   38   68   16    8   33   96  ...    7   65   69   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295    5  109   41   40   61   23   26   53   11   37  ...   19   59   72   
296   98  109   77   12   89    7   12   71   30  108  ...  103   64   46   
297   75   36    8   79   26   57   94   18   13   88  ...   29   16   50   
298   80   90   67   66   80   16   14   41   84   16  ...   69   67   80   
299   16    4   31  108   41   85   27   11  102  103  ...  100   96    2   

     393  394  395  396  397  398  399  
0     84   32   52  109   35   59   87  
1     24   91   22    2  106    4   62  
2    105    2  107   58   12   31   36  
3     13   19   68   53   84   18   57  
4     84   48    5   55   62   64   86  
..   ...  ...  ...  ...  ...  ...  ...  
295   79   72   28   47  107   90   17  
296  104   14   27   65   89   62   19  
297    4   98   36   39   94    3   12  
298   50   10   11    6  102    3   72  
299   15   68   74   10   41    9   69  

[300 rows x 400 columns]

In [109]:
# To store generated dataFrame into a csv file:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('random.csv')

In [110]:
# Switch of different shape: using reshpae()
# reshape() >> Can be used vastly in image processing.
arr = np.random.rand(3,4) 


In [111]:
arr

array([[0.04339066, 0.45437937, 0.45515479, 0.67175848],
       [0.71716659, 0.58819453, 0.8205792 , 0.16050274],
       [0.98615826, 0.74466398, 0.62602068, 0.92760159]])

In [113]:
# Total 12 data available : needs to be multiple of data
arr.reshape(6,2)

array([[0.04339066, 0.45437937],
       [0.45515479, 0.67175848],
       [0.71716659, 0.58819453],
       [0.8205792 , 0.16050274],
       [0.98615826, 0.74466398],
       [0.62602068, 0.92760159]])

In [114]:
arr.reshape(6,-1) #understood other as 2-D array

array([[0.04339066, 0.45437937],
       [0.45515479, 0.67175848],
       [0.71716659, 0.58819453],
       [0.8205792 , 0.16050274],
       [0.98615826, 0.74466398],
       [0.62602068, 0.92760159]])

In [115]:
arr.reshape(6,-12343432423344)

array([[0.04339066, 0.45437937],
       [0.45515479, 0.67175848],
       [0.71716659, 0.58819453],
       [0.8205792 , 0.16050274],
       [0.98615826, 0.74466398],
       [0.62602068, 0.92760159]])

In [116]:
# To fetch data from any given array:

arr1 = arr.reshape(6,-12343432423344)

In [120]:
# fetch data from 2nd row- 2nd col
arr1[1][1]

0.6717584791733441

In [122]:
# fetch data from 2nd column > 3,4,5 rows
# Any sub-string can be fetched
arr1[2:5,1] #[rows, column] >> slicing rows

array([0.58819453, 0.16050274, 0.74466398])

In [125]:
# To fetch conditional data from array.
arr = np.random.randint(1,100,(5,5))

In [126]:
arr

array([[ 8, 88, 86, 14, 24],
       [83, 44, 61, 27,  4],
       [50, 79, 49,  1, 50],
       [ 2, 76,  7, 21, 31],
       [11, 65, 24, 43, 57]])

In [128]:
# fetch elements whose value more than 50
arr[arr > 50]

array([88, 86, 83, 61, 79, 76, 65, 57])

In [129]:
# To fetch specific intersection of (row x col) data:

arr[2:4,[1,2]]  #[rows(slicing), columns]

array([[79, 49],
       [76,  7]])

In [131]:
# fetch first index data and reassign other value:
arr[0][0] = 5000

In [132]:
arr

array([[5000,   88,   86,   14,   24],
       [  83,   44,   61,   27,    4],
       [  50,   79,   49,    1,   50],
       [   2,   76,    7,   21,   31],
       [  11,   65,   24,   43,   57]])

# Some in-built mathematical functions of numpy:

In [144]:
arr1 = np.random.randint(1,3,[3,3])
arr2 = np.random.randint(1,3,[3,3])

In [145]:
arr1

array([[2, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [146]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [147]:
# Addition of two arrays: index- index mapping
arr1+arr2

array([[3, 4, 2],
       [3, 2, 2],
       [3, 3, 3]])

In [148]:
# Subtraction:
arr1-arr2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [149]:
# Division:
arr1/arr2

array([[2., 1., 1.],
       [2., 1., 1.],
       [2., 2., 2.]])

In [150]:
# Product: Simple index wise multiplication:
arr1*arr2

array([[2, 4, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [151]:
# # Now matrix multiplication:  @ used for matrix mul.
# mxn  pxq
# col of 1st matrix(n) ==(p) row of 2nd matrix :> multiplication condition
# mxq
arr1@arr2

array([[5, 7, 5],
       [4, 6, 4],
       [6, 8, 6]])

In [152]:
# Divide by 0 == produces inf
arr1/0

/tmp/ipykernel_124/1802407884.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [153]:
# Add some value to each element
arr1 +100

array([[102, 102, 101],
       [102, 101, 101],
       [102, 102, 102]])

In [154]:
# Square of each element:
arr1**2

array([[4, 4, 1],
       [4, 1, 1],
       [4, 4, 4]])

# Broad-casting in NumPy:

In [156]:
arr = np.zeros((4,4))

In [157]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
row = np.array([1,2,3,4])

In [159]:
row

array([1, 2, 3, 4])

In [160]:
#Broadcasting >>  Maps linear array value to defined array 
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [165]:
# Can be possible with columns also: Need to rotate the linear array then broadcast
# 1-D array can't be transposed.
row.T

array([1, 2, 3, 4])

In [166]:
# Creating col :
col = np.array([[1,2,3,4]])

In [167]:
col

array([[1, 2, 3, 4]])

In [173]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [174]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [177]:
# Some more mathematical functions:
arr1 = np.random.randint(1,4,(3,4))

In [178]:
arr1

array([[3, 1, 2, 1],
       [2, 1, 1, 1],
       [2, 3, 1, 1]])

In [179]:
# To fetch square root of elements:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ],
       [1.41421356, 1.73205081, 1.        , 1.        ]])

In [180]:
# To calculate exponent:
np.exp(arr1)

array([[20.08553692,  2.71828183,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692,  2.71828183,  2.71828183]])

In [181]:
# To calculate log:
np.log10(arr1)

array([[0.47712125, 0.        , 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ],
       [0.30103   , 0.47712125, 0.        , 0.        ]])