# Numpy: Array-manipulation:

In [2]:
import numpy as np
#Numpy was created mainly for performing mathematical operations

In [3]:
arr = np.random.randint(1,10,[3,4])

In [4]:
arr

array([[1, 2, 8, 1],
       [8, 8, 6, 8],
       [3, 6, 7, 9]])

In [5]:
# Changing shape of array:
arr.reshape(6,2)

array([[1, 2],
       [8, 1],
       [8, 8],
       [6, 8],
       [3, 6],
       [7, 9]])

In [6]:
arr.reshape(2,6)

array([[1, 2, 8, 1, 8, 8],
       [6, 8, 3, 6, 7, 9]])

In [7]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [8]:
arr.reshape(2,-212)

array([[1, 2, 8, 1, 8, 8],
       [6, 8, 3, 6, 7, 9]])

In [9]:
# Transpose of array:
arr.T

array([[1, 8, 3],
       [2, 8, 6],
       [8, 6, 7],
       [1, 8, 9]])

In [10]:
arr

array([[1, 2, 8, 1],
       [8, 8, 6, 8],
       [3, 6, 7, 9]])

In [11]:
# To convert into 1-D linear array:
arr.flatten()

array([1, 2, 8, 1, 8, 8, 6, 8, 3, 6, 7, 9])

In [12]:
arr1 = np.array([1,2,3,3,4])

In [13]:
arr1.ndim

1

In [14]:
# To convert 1-D to 2D array  (axis=0 ->row & axis=1 ->column)
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [15]:
arr

array([[1, 2, 8, 1],
       [8, 8, 6, 8],
       [3, 6, 7, 9]])

In [17]:
data = np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
# Convert single element into 1-D linear array
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 3, 4])

In [21]:
# To repeat all elements with given no. of times
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
# Shifting all elements by n places 
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [23]:
np.roll(arr1,3)

array([3, 3, 4, 1, 2])

In [24]:
# To keep elements in diagonal position and fill rest with 0s
#>> convert 1-D into 2-D
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# Numpy -> Binary Operators
+,-,/,*

In [25]:
arr1 = np.random.randint(1,10,[3,4])

In [26]:
arr2 = np.random.randint(1,10,[3,4])

In [27]:
arr1

array([[9, 2, 1, 9],
       [8, 9, 1, 3],
       [2, 8, 3, 4]])

In [28]:
arr2

array([[3, 1, 1, 5],
       [7, 9, 3, 9],
       [8, 8, 1, 7]])

In [29]:
# Index wise addition:
arr1 + arr2

array([[12,  3,  2, 14],
       [15, 18,  4, 12],
       [10, 16,  4, 11]])

In [30]:
# Element wise- index wise multiplication
arr1 * arr2

array([[27,  2,  1, 45],
       [56, 81,  3, 27],
       [16, 64,  3, 28]])

In [31]:
# Division
arr1 / arr2

array([[3.        , 2.        , 1.        , 1.8       ],
       [1.14285714, 1.        , 0.33333333, 0.33333333],
       [0.25      , 1.        , 3.        , 0.57142857]])

In [32]:
# Subtraction
arr1 / arr2

array([[3.        , 2.        , 1.        , 1.8       ],
       [1.14285714, 1.        , 0.33333333, 0.33333333],
       [0.25      , 1.        , 3.        , 0.57142857]])

In [33]:
# Remainder operation
arr1 % arr2

array([[0, 0, 0, 4],
       [1, 0, 1, 3],
       [2, 0, 0, 4]])

In [34]:
# Power calculation:
arr1 ** arr2

array([[      729,         2,         1,     59049],
       [  2097152, 387420489,         1,     19683],
       [      256,  16777216,         3,     16384]])

In [35]:
# AND Operation
arr1 & arr2

array([[1, 0, 1, 1],
       [0, 9, 1, 1],
       [0, 8, 1, 4]])

In [37]:
# OR operation
arr1 | arr2

array([[11,  3,  1, 13],
       [15,  9,  3, 11],
       [10,  8,  3,  7]])

In [36]:
# Negate operation > convert all elements into -ve value
~arr1

array([[-10,  -3,  -2, -10],
       [ -9, -10,  -2,  -4],
       [ -3,  -9,  -4,  -5]])

In [38]:
# Greater than : match with corresponding elements
arr1 > arr2

array([[ True,  True, False,  True],
       [ True, False, False, False],
       [False, False,  True, False]])

In [39]:
# Less than : match with index of corresponding elements:
arr1 < arr2

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True, False, False,  True]])

# Numpy --> String Functions

In [44]:
arr = np.array(['suharsh','kumar']) #dtype : U7 equivalent to string

In [45]:
# Convert to upper case:
np.char.upper(arr)

array(['SUHARSH', 'KUMAR'], dtype='<U7')

In [46]:
# Convert to Title case:
np.char.title(arr)

array(['Suharsh', 'Kumar'], dtype='<U7')

In [47]:
# Convert to capitalize:
np.char.capitalize(arr)

array(['Suharsh', 'Kumar'], dtype='<U7')

# Numpy --> Mathematical functions

ex: sin, cos, tan, cosin, tangent

In [48]:
arr1

array([[9, 2, 1, 9],
       [8, 9, 1, 3],
       [2, 8, 3, 4]])

In [49]:
# To calculate sin of each element:
np.sin(arr1)

array([[ 0.41211849,  0.90929743,  0.84147098,  0.41211849],
       [ 0.98935825,  0.41211849,  0.84147098,  0.14112001],
       [ 0.90929743,  0.98935825,  0.14112001, -0.7568025 ]])

In [50]:
# To calculate cos:
np.cos(arr1)

array([[-0.91113026, -0.41614684,  0.54030231, -0.91113026],
       [-0.14550003, -0.91113026,  0.54030231, -0.9899925 ],
       [-0.41614684, -0.14550003, -0.9899925 , -0.65364362]])

In [51]:
# To calculate tan:
np.tan(arr1)

array([[-0.45231566, -2.18503986,  1.55740772, -0.45231566],
       [-6.79971146, -0.45231566,  1.55740772, -0.14254654],
       [-2.18503986, -6.79971146, -0.14254654,  1.15782128]])

In [53]:
# Calculate hyper-tangent
np.tanh(arr1)

array([[0.99999997, 0.96402758, 0.76159416, 0.99999997],
       [0.99999977, 0.99999997, 0.76159416, 0.99505475],
       [0.96402758, 0.99999977, 0.99505475, 0.9993293 ]])

In [54]:
# Calculate log:
np.log(arr1)

array([[2.19722458, 0.69314718, 0.        , 2.19722458],
       [2.07944154, 2.19722458, 0.        , 1.09861229],
       [0.69314718, 2.07944154, 1.09861229, 1.38629436]])

In [55]:
# Calculate exponent:
np.exp(arr1)

array([[8.10308393e+03, 7.38905610e+00, 2.71828183e+00, 8.10308393e+03],
       [2.98095799e+03, 8.10308393e+03, 2.71828183e+00, 2.00855369e+01],
       [7.38905610e+00, 2.98095799e+03, 2.00855369e+01, 5.45981500e+01]])

In [56]:
# Calculate square root of each element:
np.sqrt(arr1)

array([[3.        , 1.41421356, 1.        , 3.        ],
       [2.82842712, 3.        , 1.        , 1.73205081],
       [1.41421356, 2.82842712, 1.73205081, 2.        ]])

In [58]:
# To calculate power of all elements:
np.power(arr1,2)

array([[81,  4,  1, 81],
       [64, 81,  1,  9],
       [ 4, 64,  9, 16]])

In [59]:
# Calculate mean:
np.mean(arr1)

4.916666666666667

In [60]:
# Calculate medain:
np.median(arr1)

3.5

In [61]:
# Calculate standard deviation:
np.std(arr1)

3.226410113767656

In [62]:
# Calculate variance:
np.var(arr1)

10.409722222222221

In [63]:
# Fetch min element:
np.min(arr1)

1

In [64]:
# Fetch max element:
np.max(arr1)

9